### ISSUE TITLE
overwriting window.location changed in 0.2.0

### ISSUE THREAD

**Issue by kellyselden** [kaliber5/ember-window-mock#33]
real code does `this.set('window.location', x);`, test code does `assert.equal(window.location, x);`

<img width="702" alt="screen shot 2017-12-27 at 9 58 55 am" src="https://user-images.githubusercontent.com/602423/34389204-2a511864-eaed-11e7-9437-17c108e2d495.png">

worked in the previous version.

**Comment by simonihmig** [comment]
It seems this actually not a bug. My findings:
* the recent refactoring of the location mock introduced a possible breaking change (hence the minor version bump), in that `window.location.href` (same for `window.location` when casted to a string) returns an URL with a trailing slash when the path is empty. But this is following the specs AFAICT. You can see this when doing `window.location = 'http://www.example.com';`. After the redirect `window.location.href` will return `'http://www.example.com/'` (note the trailing slash)
* I bet if you change your assertion to include the trailing slash, the test will pass
* the misleading error message is due to the special nature of `window.location`: it actually is an object (hence the result showing the member functions), but when casted to a string it returns the `window.location.href` URL string (see https://github.com/kaliber5/ember-window-mock/blob/master/addon-test-support/-private/mock/location.js#L43-L45, same for the real thing). When comparing it to a string, `toString`will be called, but when QUnit outputs the actual value, no string conversion takes place. Unfortunately I don't think we can optimize that, can we?
* using `window.location.href` for the assertion won't show this issue, as this is always a string
* all of this did not really change in the 0.2.0 version. Just the slightly different result (trailing slash) probably uncovered this in your tests

**Comment by kellyselden** [comment]
Trailing slash made no difference, but we switched to assert against window.location.href and now all is good. Thanks.
