### ISSUE TITLE
optional window service in addon

### ISSUE THREAD

**Issue by kellyselden** [kaliber5/ember-window-mock#52]
We have an addon with an optional dependency of ember-window-mock. The service injection is:

```js
  window: computed(function() {
    return getOwner(this).lookup('service:window');
  }),
```

How would we do this in 0.3+? Is it entirely up to the app to inject a mocked window?

**Comment by simonihmig** [comment]
Not sure. The newer version doesn't have a service anymore, you just import it: `import window from 'ember-window-mock';`.

When you use that, instead of the CP as in your example, does the import then break things when the addon is not present (being an optional dependency). Is that your issue?

Also, to understand your use case, why does it have to be an optional dependency? As this addon practically does not add any runtime overhead, can't you just make it a strict dependency?

**Comment by kellyselden** [comment]
> When you use that, instead of the CP as in your example, does the import then break things when the addon is not present (being an optional dependency). Is that your issue?

Yes, the import will break when it's missing.

> Also, to understand your use case, why does it have to be an optional dependency? As this addon practically does not add any runtime overhead, can't you just make it a strict dependency?

It doesn't seem right to have a testing library as a direct dependency. I would like to keep it out of the normal build.

**Comment by buschtoens** [comment]
Assuming we'd use an injection again, you'd still need to add fallback logic for the non-mock scenario, like:

```js
  window: computed(function() {
    return getOwner(this).lookup('service:window') || window;
  }),
```

Right?

You could do something similar for your addon with the current module implementation:

```js
// your-addon/addon/window.js

let windowExport = window;

try {
  windowExport = require('ember-window-mock').default;
} catch (error) {
  // `ember-window-mock` is not included
}

export default windowExport;
```

`require` is a global from [`loader.js`](https://github.com/ember-cli/loader.js).

This way you can keep this dependency as a `devDependency`.
